/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import codigos.Horario;
import codigos.Mensagem;
import codigos.Motorista;
import codigos.Passageiro;
import codigos.Usuario;
import java.awt.CardLayout;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.util.Iterator;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableModel;
import model.dao.Hor_passDAO;
import model.dao.MensagemDAO;
import model.dao.MotoristaDAO;
import model.dao.PassageiroDAO;
import model.dao.UsuarioDAO;

/**
 *
 * @author juliana
 */
public class telaPassageiro extends javax.swing.JFrame {

    /**
     * Creates new form telaPassageiro
     */
    int passageiroID;
    public telaPassageiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tela2 = new javax.swing.JPanel();
        TelaInicio = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        bemVindoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MensagensRecebidas = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaRecebidas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        MensagensEnviadas = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaEnviadas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Informações = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        info = new javax.swing.JTextArea();
        BuscarMotoristaNome = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        buscaNomeMotorista = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        resultadoBuscaMotorista = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        SolicitarHorario = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        selecionarDia = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        MostrarHorarios = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelaHorarios = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        Tela2.setBackground(new java.awt.Color(245, 248, 249));
        Tela2.setLayout(new java.awt.CardLayout());

        jPanel5.setBackground(new java.awt.Color(245, 248, 249));

        bemVindoLabel.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

        jLabel1.setText("Selecione as opções acima para navegar no aplicativo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(bemVindoLabel))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(bemVindoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        TelaInicio.setViewportView(jPanel5);

        Tela2.add(TelaInicio, "ini");

        jPanel2.setBackground(new java.awt.Color(245, 248, 249));

        tabelaRecebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Remetente", "Horário", "Mensagem"
            }
        ));
        jScrollPane3.setViewportView(tabelaRecebidas);
        if (tabelaRecebidas.getColumnModel().getColumnCount() > 0) {
            tabelaRecebidas.getColumnModel().getColumn(0).setMinWidth(180);
            tabelaRecebidas.getColumnModel().getColumn(0).setPreferredWidth(180);
            tabelaRecebidas.getColumnModel().getColumn(0).setMaxWidth(180);
            tabelaRecebidas.getColumnModel().getColumn(1).setMinWidth(80);
            tabelaRecebidas.getColumnModel().getColumn(1).setPreferredWidth(80);
            tabelaRecebidas.getColumnModel().getColumn(1).setMaxWidth(80);
        }

        jLabel4.setText("Recebidas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(0, 110, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        MensagensRecebidas.setViewportView(jPanel2);

        Tela2.add(MensagensRecebidas, "mensr");

        jPanel1.setBackground(new java.awt.Color(245, 248, 249));

        tabelaEnviadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Destinatário", "Horário", "Mensagem"
            }
        ));
        jScrollPane2.setViewportView(tabelaEnviadas);
        if (tabelaEnviadas.getColumnModel().getColumnCount() > 0) {
            tabelaEnviadas.getColumnModel().getColumn(0).setMinWidth(150);
            tabelaEnviadas.getColumnModel().getColumn(0).setPreferredWidth(150);
            tabelaEnviadas.getColumnModel().getColumn(0).setMaxWidth(150);
            tabelaEnviadas.getColumnModel().getColumn(1).setMinWidth(80);
            tabelaEnviadas.getColumnModel().getColumn(1).setPreferredWidth(80);
            tabelaEnviadas.getColumnModel().getColumn(1).setMaxWidth(80);
        }

        jLabel5.setText("Enviadas");

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jButton1.setText("Nova mensagem");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        MensagensEnviadas.setViewportView(jPanel1);

        Tela2.add(MensagensEnviadas, "mense");

        jPanel3.setBackground(new java.awt.Color(245, 248, 249));

        jLabel2.setText("Informações sobre a conta");

        info.setEditable(false);
        info.setColumns(20);
        info.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        info.setRows(5);
        jScrollPane1.setViewportView(info);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        Informações.setViewportView(jPanel3);

        Tela2.add(Informações, "inf");

        jPanel4.setBackground(new java.awt.Color(245, 248, 249));

        jLabel8.setText("Nome do motorista");

        buscaNomeMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaNomeMotoristaActionPerformed(evt);
            }
        });
        buscaNomeMotorista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscaNomeMotoristaKeyPressed(evt);
            }
        });

        resultadoBuscaMotorista.setEditable(false);
        resultadoBuscaMotorista.setColumns(20);
        resultadoBuscaMotorista.setRows(5);
        jScrollPane5.setViewportView(resultadoBuscaMotorista);

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Resultados da busca");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(buscaNomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscaNomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );

        BuscarMotoristaNome.setViewportView(jPanel4);

        Tela2.add(BuscarMotoristaNome, "buscarnome");

        jPanel6.setBackground(new java.awt.Color(245, 248, 249));

        jLabel10.setText("Horário");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton3.setText("Solicitar");

        selecionarDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado" }));

        jLabel6.setText("Selecione o dia");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(selecionarDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selecionarDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel10)
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        SolicitarHorario.setViewportView(jPanel6);

        Tela2.add(SolicitarHorario, "solicitah");

        jPanel7.setBackground(new java.awt.Color(245, 248, 249));

        jLabel11.setText("Horários atuais");

        tabelaHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Início", "Fim"
            }
        ));
        jScrollPane6.setViewportView(tabelaHorarios);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(93, 93, 93)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MostrarHorarios.setViewportView(jPanel7);

        Tela2.add(MostrarHorarios, "mostrah");

        jMenu1.setText("Passageiro");

        jMenuItem6.setText("Inicio");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem1.setText("Mensagens Recebidas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem8.setText("Mensagens Enviadas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem2.setText("Informações");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem7.setText("Sair");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Motorista");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Buscar por nome");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Horários");

        jMenuItem10.setText("Confirmar horário");
        jMenu3.add(jMenuItem10);

        jMenuItem4.setText("Solicitar horário");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Mostrar horários");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tela2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tela2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        MensagemDAO mdao = new MensagemDAO();
        PassageiroDAO pas = new PassageiroDAO();
        Usuario u;
        u = pas.buscar(passageiroID);
        LinkedList ll = mdao.msgRecebidas(u);
        Iterator i = ll.iterator();
        DefaultTableModel modelo = (DefaultTableModel) tabelaRecebidas.getModel();
        modelo.setNumRows(0);
        Mensagem m;
        int indexRow = 0;
        while (i.hasNext()) {
            indexRow++;
            m = (Mensagem)i.next();
            modelo.addRow(new Object[] {
                m.getRemetente().getNome()+"("+m.getRemetente().getLogin()+")",
                m.getDataHora(),
                formatTxtForShowInTable(m.getConteudo())
            });
            tabelaRecebidas.setRowHeight(100);
            scrollCellToView(indexRow, 3);
        }
        
        CardLayout cl = (CardLayout) Tela2.getLayout();
        cl.show(Tela2, "mensr");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        String informacoes;
        Passageiro p;
        PassageiroDAO pdao = new PassageiroDAO();
        p = pdao.buscar(passageiroID);
        informacoes = "\nNome: "+p.getNome()+"\n\nData de Nascimento" +""+ "\n\nCpf: "+p.getCpf()+ 
                "\n\nEndereço: " +p.getEnderecoResidencia()+"\n\nCep: "+p.getCep();
        info.setText(informacoes);
        CardLayout cl = (CardLayout) Tela2.getLayout();
        cl.show(Tela2, "inf");
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Tela2.getLayout();
        cl.show(Tela2, "bum");
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Tela2.getLayout();
        cl.show(Tela2, "solicitah");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Hor_passDAO hdao = new Hor_passDAO();
        LinkedList ll = hdao.mostrarHorarioPassageiro(passageiroID);
        Iterator i = ll.iterator();
        DefaultTableModel modelo = (DefaultTableModel) tabelaHorarios.getModel();
        while (i.hasNext()) {
            Horario h;
            h = (Horario)i.next();
            modelo.addRow(new Object[] {h.getHoraInicio(),
                                        h.getHoraFinal()});
        }
        CardLayout cl = (CardLayout) Tela2.getLayout();
        cl.show(Tela2, "mostrah");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Tela2.getLayout();
        cl.show(Tela2, "ini");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        NovaMensagemPassageiro nvp = new NovaMensagemPassageiro();
        nvp.setVisible(true);
        nvp.recebeID(passageiroID);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        MensagemDAO mdao = new MensagemDAO();
        PassageiroDAO mot = new PassageiroDAO();
        Usuario u;
        u = mot.buscar(passageiroID);
        LinkedList ll = mdao.msgEnviadas(u);
        Iterator i = ll.iterator();
        DefaultTableModel modelo = (DefaultTableModel) tabelaEnviadas.getModel();
        modelo.setNumRows(0);
        Mensagem m;
        while (i.hasNext()) {
            m = (Mensagem)i.next();
            modelo.addRow(new Object[] {
                m.getDestinatario().getNome()+"("+m.getDestinatario().getLogin()+")",
                m.getDataHora(),
                formatTxtForShowInTable(m.getConteudo())
            });
            tabelaEnviadas.setRowHeight(100);
        }
        
        CardLayout cl = (CardLayout) Tela2.getLayout();
        cl.show(Tela2, "mense");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    public void scrollCellToView(int rowIndex, int vColIndex) {
    if (!(this.getParent() instanceof JViewport)) {
        return;
    }
    JViewport viewport = (JViewport) this.getParent();
    Rectangle rect = tabelaRecebidas.getCellRect(rowIndex, vColIndex, true);
    Rectangle viewRect = viewport.getViewRect();

    int x = viewRect.x;
    int y = viewRect.y;

    if (rect.x >= viewRect.x && rect.x <= (viewRect.x + viewRect.width - rect.width)){

    } else if (rect.x < viewRect.x){
        x = rect.x;
    } else if (rect.x > (viewRect.x + viewRect.width - rect.width)) {
        x = rect.x - viewRect.width + rect.width;
    }

    if (rect.y >= viewRect.y && rect.y <= (viewRect.y + viewRect.height - rect.height)){

    } else if (rect.y < viewRect.y){
        y = rect.y;
    } else if (rect.y > (viewRect.y + viewRect.height - rect.height)){
        y = rect.y - viewRect.height + rect.height;
    }

    viewport.setViewPosition(new Point(x,y));
}
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Tela2.getLayout();
        cl.show(Tela2, "buscarnome");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void buscaNomeMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaNomeMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaNomeMotoristaActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        UsuarioDAO udao = new UsuarioDAO();
        LinkedList ll = udao.buscar(buscaNomeMotorista.getText());
        Iterator i = ll.iterator();
        if (!ll.isEmpty()) {
            MotoristaDAO p = new MotoristaDAO();
            Usuario u;
            String text = "\n";
            while (i.hasNext()) {
                u = (Usuario) i.next();
                if (p.verificaMotorista(u.getId()) != -1) {
                    MotoristaDAO mdao = new MotoristaDAO();
                    Motorista m;
                    int id = mdao.verificaMotorista(u.getId());
                    m = mdao.buscar(id);
                    text = text+"Login: "+ m.getLogin()+"\nRegião: "+m.getRegiao()+"\n";
                }
            }
            resultadoBuscaMotorista.setText(text);
            if (text.equals("\n")) {
                JOptionPane.showMessageDialog(null, "Motorista não encontrado!");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buscaNomeMotoristaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscaNomeMotoristaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            UsuarioDAO udao = new UsuarioDAO();
            LinkedList ll = udao.buscar(buscaNomeMotorista.getText());
            Iterator i = ll.iterator();
            if (!ll.isEmpty()) {
                MotoristaDAO p = new MotoristaDAO();
                Usuario u;
                String text = "\n";
                while (i.hasNext()) {
                    u = (Usuario) i.next();
                    if (p.verificaMotorista(u.getId()) != -1) {
                        MotoristaDAO mdao = new MotoristaDAO();
                        Motorista m;
                        int id = mdao.verificaMotorista(u.getId());
                        m = mdao.buscar(id);
                        text = text+"\nLogin: "+ m.getLogin()+"\nRegião: "+m.getRegiao()+"\n";
                    }
                }
                resultadoBuscaMotorista.setText(text);
                
            }
            else {
                
                JOptionPane.showMessageDialog(null, "Motorista não encontrado!");
                
            }
        }
    }//GEN-LAST:event_buscaNomeMotoristaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPassageiro().setVisible(true);
            }
        });
        
        
    }
    
    public void recebeID (int id) {
        this.passageiroID = id;
        PassageiroDAO pdao = new PassageiroDAO();
        Passageiro p;
        p = pdao.buscar(passageiroID);
        bemVindoLabel.setText("Seja bem vindo(a) " + p.getNome()+",");
    }
    
    public String formatTxtForShowInTable(String txt){
		String txtFormated = "<HTML><P ALIGN=LEFT>";		
		String endTag = "<BR></P></HTML>";
		String jumpTag = "<BR>";		
		int count = 1;
		int i = 0;
		int lineSize = 70;
		int tempInt = txt.length()/lineSize;
		while (count <= tempInt){			
			txtFormated = txtFormated + txt.substring(i, (lineSize*count)) + jumpTag;
			i = i + lineSize;
			count++;
		}
		if (txt.length()%lineSize != 0){
			txtFormated = txtFormated + txt.substring(i);
		}
		txtFormated = txtFormated + endTag;
		return txtFormated;
	}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane BuscarMotoristaNome;
    private javax.swing.JScrollPane Informações;
    private javax.swing.JScrollPane MensagensEnviadas;
    private javax.swing.JScrollPane MensagensRecebidas;
    private javax.swing.JScrollPane MostrarHorarios;
    private javax.swing.JScrollPane SolicitarHorario;
    private javax.swing.JPanel Tela2;
    private javax.swing.JScrollPane TelaInicio;
    private javax.swing.JLabel bemVindoLabel;
    private javax.swing.JTextField buscaNomeMotorista;
    private javax.swing.JTextArea info;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea resultadoBuscaMotorista;
    private javax.swing.JComboBox<String> selecionarDia;
    private javax.swing.JTable tabelaEnviadas;
    private javax.swing.JTable tabelaHorarios;
    private javax.swing.JTable tabelaRecebidas;
    // End of variables declaration//GEN-END:variables
}
