package views;

import codigos.Horario;
import codigos.Mensagem;
import codigos.Motorista;
import codigos.Passageiro;
import codigos.Usuario;
import codigos.Veiculo;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.dao.Hor_motDAO;
import model.dao.HorarioDAO;
import model.dao.MensagemDAO;
import model.dao.Mot_passDAO;
import model.dao.Mot_veiDAO;
import model.dao.MotoristaDAO;
import model.dao.PassageiroDAO;
import model.dao.UsuarioDAO;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;

public class telaMotorista extends javax.swing.JFrame {
    
    int motoristaID;
    int veiculoID;
    /**
     * Creates new form telaMotorista
     */
    public telaMotorista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tela3 = new javax.swing.JPanel();
        Inicio = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        bemVindoLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        GerarContrato = new javax.swing.JScrollPane();
        jPanel13 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        gerarContratoCombo = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        Confirmacao = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        confirmarCombo = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        Desconfirmar = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        desconfirmaCombo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        MensagensEnviadas = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        NovaMensagem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaEnviadas = new javax.swing.JTable();
        MensagensRecebidas = new javax.swing.JScrollPane();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelaRecebidas = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        Informações = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        informacoes = new javax.swing.JTextArea();
        AdicionarPassageiro = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        buscaNome = new javax.swing.JTextField();
        botaoBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PassageirosComboBox = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        RemoverPassageiro = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        botaoRemove = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        BuscarPassageiroNome = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        buscaPassageiroNome = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultadoPassageiroNome = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        AdicionarHorario = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        horaInicioCad = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        horaFinalCad = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        diaCombo = new javax.swing.JComboBox<>();
        RemoverHorario = new javax.swing.JScrollPane();
        jPanel12 = new javax.swing.JPanel();
        removerHorarioCombo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        MostrarHorario = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelaHorarioIF = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        Tela3.setBackground(new java.awt.Color(245, 248, 249));
        Tela3.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(245, 248, 249));

        bemVindoLabel.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

        jLabel4.setText("Selecione as opções acima para navegar no aplicativo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(bemVindoLabel))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(bemVindoLabel)
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        Inicio.setViewportView(jPanel2);

        Tela3.add(Inicio, "ini");

        jPanel13.setBackground(new java.awt.Color(245, 248, 249));

        jLabel18.setText("Escolha o passageiro para gerar o contrato");

        jButton8.setText("Gerar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(gerarContratoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gerarContratoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        GerarContrato.setViewportView(jPanel13);

        Tela3.add(GerarContrato, "gerarContrato");

        jPanel1.setBackground(new java.awt.Color(245, 248, 249));

        jLabel16.setText("Abrir para confirmação");

        jButton4.setText("Abrir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(confirmarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        Confirmacao.setViewportView(jPanel1);

        Tela3.add(Confirmacao, "confirmacao");

        jPanel10.setBackground(new java.awt.Color(245, 248, 249));

        jLabel15.setText("Fechar confirmação");

        jButton6.setText("Desconfirmar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(desconfirmaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addContainerGap(428, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desconfirmaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        Desconfirmar.setViewportView(jPanel10);

        Tela3.add(Desconfirmar, "desconfirmar");

        jPanel3.setBackground(new java.awt.Color(245, 248, 249));

        NovaMensagem.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        NovaMensagem.setText("Nova mensagem");
        NovaMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaMensagemActionPerformed(evt);
            }
        });

        jLabel5.setText("Enviadas");

        tabelaEnviadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Destinatário", "Horário", "Mensagem"
            }
        ));
        tabelaEnviadas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tabelaEnviadas.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(tabelaEnviadas);
        if (tabelaEnviadas.getColumnModel().getColumnCount() > 0) {
            tabelaEnviadas.getColumnModel().getColumn(0).setMinWidth(150);
            tabelaEnviadas.getColumnModel().getColumn(0).setPreferredWidth(150);
            tabelaEnviadas.getColumnModel().getColumn(0).setMaxWidth(150);
            tabelaEnviadas.getColumnModel().getColumn(1).setMinWidth(80);
            tabelaEnviadas.getColumnModel().getColumn(1).setPreferredWidth(80);
            tabelaEnviadas.getColumnModel().getColumn(1).setMaxWidth(80);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NovaMensagem)
                            .addComponent(jLabel5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(NovaMensagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        MensagensEnviadas.setViewportView(jPanel3);

        Tela3.add(MensagensEnviadas, "mense");

        jPanel11.setBackground(new java.awt.Color(245, 248, 249));

        tabelaRecebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Remetente", "Horário", "Mensagem"
            }
        ));
        jScrollPane7.setViewportView(tabelaRecebidas);
        if (tabelaRecebidas.getColumnModel().getColumnCount() > 0) {
            tabelaRecebidas.getColumnModel().getColumn(0).setMinWidth(180);
            tabelaRecebidas.getColumnModel().getColumn(0).setPreferredWidth(180);
            tabelaRecebidas.getColumnModel().getColumn(0).setMaxWidth(180);
            tabelaRecebidas.getColumnModel().getColumn(1).setMinWidth(80);
            tabelaRecebidas.getColumnModel().getColumn(1).setPreferredWidth(80);
            tabelaRecebidas.getColumnModel().getColumn(1).setMaxWidth(80);
        }

        jLabel11.setText("Recebidas");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        MensagensRecebidas.setViewportView(jPanel11);

        Tela3.add(MensagensRecebidas, "mensr");

        jPanel4.setBackground(new java.awt.Color(245, 248, 249));

        jLabel1.setText("Informações sobre a conta");

        informacoes.setEditable(false);
        informacoes.setColumns(20);
        informacoes.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        informacoes.setRows(5);
        jScrollPane1.setViewportView(informacoes);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Informações.setViewportView(jPanel4);

        Tela3.add(Informações, "inf");

        jPanel5.setBackground(new java.awt.Color(245, 248, 249));

        jLabel14.setText("Nome do passageiro que deseja adicionar");

        buscaNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscaNomeKeyPressed(evt);
            }
        });

        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Escolha pelo login");

        jButton3.setText("Adicionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel14)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PassageirosComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buscaNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoBuscar)
                            .addComponent(jButton3))))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscar))
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassageirosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        AdicionarPassageiro.setViewportView(jPanel5);

        Tela3.add(AdicionarPassageiro, "addp");

        jPanel6.setBackground(new java.awt.Color(245, 248, 249));

        jLabel3.setText("Escolha pelo login");

        jButton5.setText("Remover");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(botaoRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(261, Short.MAX_VALUE))
        );

        RemoverPassageiro.setViewportView(jPanel6);

        Tela3.add(RemoverPassageiro, "rmp");

        jPanel7.setBackground(new java.awt.Color(245, 248, 249));

        jLabel12.setText("Nome do passageiro");

        buscaPassageiroNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaPassageiroNomeActionPerformed(evt);
            }
        });
        buscaPassageiroNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscaPassageiroNomeKeyPressed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        resultadoPassageiroNome.setEditable(false);
        resultadoPassageiroNome.setColumns(20);
        resultadoPassageiroNome.setRows(5);
        jScrollPane3.setViewportView(resultadoPassageiroNome);

        jLabel13.setText("Resultados da pesquisa");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(buscaPassageiroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscaPassageiroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        BuscarPassageiroNome.setViewportView(jPanel7);

        Tela3.add(BuscarPassageiroNome, "buscarnome");

        jPanel8.setBackground(new java.awt.Color(245, 248, 249));

        jLabel9.setText("Informe o novo horário");

        try {
            horaInicioCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        horaInicioCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaInicioCadActionPerformed(evt);
            }
        });

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        try {
            horaFinalCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Inicial");

        jLabel7.setText("Final");

        jLabel8.setText("Selecione o dia");

        diaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Domingo", "Segunda-feira", "Terça-feira", "Quarta-feira", "Quinta-feira", "Sexta-feira", "Sábado" }));
        diaCombo.setToolTipText("");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(diaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(horaFinalCad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(horaInicioCad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(191, 191, 191))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel9))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(61, 61, 61)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(horaInicioCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(diaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(horaFinalCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(190, 190, 190))
        );

        AdicionarHorario.setViewportView(jPanel8);

        Tela3.add(AdicionarHorario, "addh");

        jPanel12.setBackground(new java.awt.Color(245, 248, 249));

        jLabel17.setText("Selecione o horário que deseja remover");

        jButton7.setText("Remover");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(removerHorarioCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removerHorarioCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        RemoverHorario.setViewportView(jPanel12);

        Tela3.add(RemoverHorario, "rmhr");

        jPanel9.setBackground(new java.awt.Color(245, 248, 249));

        tabelaHorarioIF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Início", "Fim"
            }
        ));
        jScrollPane6.setViewportView(tabelaHorarioIF);

        jLabel10.setText("Horários atuais");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(96, 96, 96)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MostrarHorario.setViewportView(jPanel9);

        Tela3.add(MostrarHorario, "mostrarh");

        jMenu3.setText("Motorista");

        jMenuItem8.setText("Inicio");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem1.setText("Mensagens Recebidas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem11.setText("Mensagens Enviadas");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem2.setText("Informações");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem13.setText("Gerar Rota");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuItem12.setText("Sair");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Passageiros");

        jMenuItem3.setText("Adicionar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Remover");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Buscar por nome");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem14.setText("Gerar contrato");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Horários");

        jMenuItem6.setText("Adicionar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem10.setText("Remover");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem9.setText("Abrir confirmação");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem15.setText("Fechar confirmação");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem15);

        jMenuItem7.setText("Mostrar horários");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tela3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tela3, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        MensagemDAO mdao = new MensagemDAO();
        MotoristaDAO mot = new MotoristaDAO();
        Usuario u;
        u = mot.buscar(motoristaID);
        LinkedList ll = mdao.msgRecebidas(u);
        Iterator i = ll.iterator();
        DefaultTableModel modelo = (DefaultTableModel) tabelaRecebidas.getModel();
        modelo.setNumRows(0);
        Mensagem m;
        while (i.hasNext()) {
            m = (Mensagem)i.next();
            modelo.addRow(new Object[] {
                m.getRemetente().getNome()+"("+m.getRemetente().getLogin()+")",
                m.getDataHora(),
                formatTxtForShowInTable(m.getConteudo())
            });
            tabelaRecebidas.setRowHeight(100);
        }
        CardLayout cl = (CardLayout) Tela3.getLayout();
        cl.show(Tela3, "mensr");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       
        CardLayout cl = (CardLayout) Tela3.getLayout();
        cl.show(Tela3, "addp");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
       
        CardLayout cl = (CardLayout) Tela3.getLayout();
        cl.show(Tela3, "ini");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        String info ;
        Motorista m;
        MotoristaDAO mdao = new MotoristaDAO();
        m = mdao.buscar(motoristaID);
        Mot_veiDAO mot = new Mot_veiDAO();
        Veiculo v;
       
        LinkedList ll = mot.veiculos(motoristaID);
        v = (Veiculo)ll.getFirst();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String data = sdf.format(m.getDataDeNascimento());
        info = "\nNome: " + m.getNome() +"\n\nData de Nascimento: "+ data +"\n\nCpf: " + m.getCpf()
                + "\n\nEndereço: " + m.getEnderecoResidencia() + "\n\nCep: "+m.getCep()+"\n\nRegião: "
                + m.getRegiao()+"\n\n\nVeículo\n\nPlaca: "+v.getPlaca()+"\nModelo: "+v.getModelo()+
                "\nCapacidade: "+v.getCapacidade();
        informacoes.setText(info);
        CardLayout cl = (CardLayout) Tela3.getLayout();
        cl.show(Tela3, "inf");
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        botaoRemove.removeAllItems();
        Mot_passDAO udao = new Mot_passDAO();
        LinkedList ll = udao.passageiros(motoristaID);
        Iterator i = ll.iterator();
        if (!ll.isEmpty()) {
            PassageiroDAO p = new PassageiroDAO();
            Passageiro u;
            while (i.hasNext()) {
                u = (Passageiro) i.next();

                botaoRemove.addItem(u);

            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Não há passageiros na sua lista!");
        }
        CardLayout cl = (CardLayout) Tela3.getLayout();
        cl.show(Tela3, "rmp");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       
        CardLayout cl = (CardLayout) Tela3.getLayout();
        cl.show(Tela3, "buscarnome");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        
        CardLayout cl = (CardLayout) Tela3.getLayout();
        cl.show(Tela3, "addh");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

        Hor_motDAO hdao = new Hor_motDAO();
        LinkedList ll = hdao.mostrarHorarioMotorista(motoristaID);
        Iterator i = ll.iterator();
        DefaultTableModel modelo = (DefaultTableModel) tabelaHorarioIF.getModel();
        modelo.setNumRows(0);
        while (i.hasNext()) {
            Horario h = (Horario)i.next();
            java.sql.Time t = h.getHoraInicio();
            java.sql.Time t1 = h.getHoraFinal();
            DateFormat df = new SimpleDateFormat("HH:mm:ss");
            String ts = df.format(t);
            String t1s = df.format(t1);
            modelo.addRow(new Object[]
                {ts, t1s} );
        }
            
        
        CardLayout cl = (CardLayout) Tela3.getLayout();
        cl.show(Tela3, "mostrarh");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void NovaMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaMensagemActionPerformed
        
        NovaMensagemMotorista nvm = new NovaMensagemMotorista();
        nvm.setVisible(true);
        nvm.recebeID(motoristaID);
        MensagemDAO mdao = new MensagemDAO();
        MotoristaDAO mot = new MotoristaDAO();
        Usuario u;
        u = mot.buscar(motoristaID);
        LinkedList ll = mdao.msgEnviadas(u);
        Iterator i = ll.iterator();
        DefaultTableModel modelo = (DefaultTableModel) tabelaEnviadas.getModel();
        modelo.setNumRows(0);
        Mensagem m;
        while (i.hasNext()) {
            m = (Mensagem)i.next();
            modelo.addRow(new Object[] {
                m.getDestinatario().getNome()+"("+m.getDestinatario().getLogin()+")",
                m.getDataHora(),
                formatTxtForShowInTable(m.getConteudo())
            });
            tabelaEnviadas.setRowHeight(100);
        }
    }//GEN-LAST:event_NovaMensagemActionPerformed

    
    
    public String formatTxtForShowInTable(String txt){
        String txtFormated = "<HTML><P ALIGN=LEFT>";		
        String endTag = "<BR></P></HTML>";
        String jumpTag = "<BR>";		
        int count = 1;
        int i = 0;
        int lineSize = 200;
        int tempInt = txt.length()/lineSize;
        while (count <= tempInt){			
                txtFormated = txtFormated + txt.substring(i, (lineSize*count)) + jumpTag;
                i = i + lineSize;
                count++;
        }
        if (txt.length()%lineSize != 0){
                txtFormated = txtFormated + txt.substring(i);
        }
        txtFormated = txtFormated + endTag;
        return txtFormated;
    }

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        
        MensagemDAO mdao = new MensagemDAO();
        MotoristaDAO mot = new MotoristaDAO();
        Usuario u;
        u = mot.buscar(motoristaID);
        LinkedList ll = mdao.msgEnviadas(u);
        Iterator i = ll.iterator();
        DefaultTableModel modelo = (DefaultTableModel) tabelaEnviadas.getModel();
        modelo.setNumRows(0);
        Mensagem m;
        while (i.hasNext()) {
            m = (Mensagem)i.next();
            modelo.addRow(new Object[] {
                m.getDestinatario().getNome()+"("+m.getDestinatario().getLogin()+")",
                m.getDataHora(),
                formatTxtForShowInTable(m.getConteudo())
            });
            tabelaEnviadas.setRowHeight(100);
        }
        
        CardLayout cl = (CardLayout) Tela3.getLayout();
        cl.show(Tela3, "mense");
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed

        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        new GoogleMaps().setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void horaInicioCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaInicioCadActionPerformed
      
    }//GEN-LAST:event_horaInicioCadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String dias = (String) diaCombo.getSelectedItem();
        int dia;
        if (dias.equals("Domingo")) {
            dia = 1;
        }
        else if (dias.equals("Segunda-feira")) {
            dia = 2;
        }
        else if (dias.equals("Terça-feira")) {
            dia = 3;
        }
        else if (dias.equals("Quarta-feira")) {
            dia = 4;
        }
        else if (dias.equals("Quinta-feira")) {
            dia = 5;
        }
        else if (dias.equals("Sexta-feira")) {
            dia = 6;
        }
        else  {
            dia = 7;
        }
        Horario h = new Horario();
        java.sql.Time t = java.sql.Time.valueOf(horaInicioCad.getText());
        java.sql.Time t1 = java.sql.Time.valueOf(horaFinalCad.getText());
        h.setHoraInicio(t);
        h.setHoraFinal(t1);
        h.setDia(dia);
        h.setTipo(true);
        HorarioDAO hdao = new HorarioDAO();
        int idH = hdao.criar(h);
        h.setId(idH);
        MotoristaDAO mdao = new MotoristaDAO();
        Motorista m;
        m = mdao.buscar(motoristaID);
        Hor_motDAO horadao = new Hor_motDAO();
        horadao.criar(h, m);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        PassageirosComboBox.removeAllItems();
        UsuarioDAO udao = new UsuarioDAO();
        LinkedList ll = udao.buscar(buscaNome.getText());
        Iterator i = ll.iterator();
        if (!ll.isEmpty()) {
            PassageiroDAO p = new PassageiroDAO();
            Usuario u;
            while (i.hasNext()) {
                u = (Usuario) i.next();
                if (p.verificaPassageiro(u.getId()) != -1) {
                    PassageiroDAO pdao = new PassageiroDAO();
                    Passageiro pa;
                    int id = pdao.verificaPassageiro(u.getId());
                    pa = pdao.buscar(id);
                    PassageirosComboBox.addItem(pa);
                }
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Passageiro não encontrado!");
        }
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void buscaNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscaNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            PassageirosComboBox.removeAllItems();
            UsuarioDAO udao = new UsuarioDAO();
            LinkedList ll = udao.buscar(buscaNome.getText());
            Iterator i = ll.iterator();
            if (!ll.isEmpty()) {
                PassageiroDAO p = new PassageiroDAO();
                Usuario u;
                while (i.hasNext()) {
                    u = (Usuario) i.next();
                    if (p.verificaPassageiro(u.getId()) != -1) {
                        PassageiroDAO pdao = new PassageiroDAO();
                        Passageiro pa;
                        int id = pdao.verificaPassageiro(u.getId());
                        pa = pdao.buscar(id);
                        PassageirosComboBox.addItem(pa);
                    }
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "Passageiro não encontrado!");
            }
        }
    }//GEN-LAST:event_buscaNomeKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Mot_passDAO mpdao = new Mot_passDAO();
        Passageiro pa;
        pa = (Passageiro)PassageirosComboBox.getSelectedItem();
        MotoristaDAO mdao = new MotoristaDAO();
        Motorista m;
        m = mdao.buscar(motoristaID);
        mpdao.criar(m, pa, true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        UsuarioDAO udao = new UsuarioDAO();
        LinkedList ll = udao.buscar(buscaPassageiroNome.getText());
        Iterator i = ll.iterator();
        if (!ll.isEmpty()) {
            PassageiroDAO p = new PassageiroDAO();
            Usuario u;
            String text = "\n";
            while (i.hasNext()) {
                u = (Usuario) i.next();
                if (p.verificaPassageiro(u.getId()) != -1) {
                    PassageiroDAO mdao = new PassageiroDAO();
                    Passageiro m;
                    int id = mdao.verificaPassageiro(u.getId());
                    m = mdao.buscar(id);
                    text = text+"Login: "+ m.getLogin()+"\nEndereço: "+m.getEnderecoResidencia()+"\n";
                }
            }
            resultadoPassageiroNome.setText(text);
            
        }
        else {        
            JOptionPane.showMessageDialog(null, "Passageiro não encontrado!");    
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buscaPassageiroNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscaPassageiroNomeKeyPressed
       
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            UsuarioDAO udao = new UsuarioDAO();
            LinkedList ll = udao.buscar(buscaPassageiroNome.getText());
            Iterator i = ll.iterator();
            if (!ll.isEmpty()) {
                PassageiroDAO p = new PassageiroDAO();
                Usuario u;
                String text = "\n";
                while (i.hasNext()) {
                    u = (Usuario) i.next();
                    if (p.verificaPassageiro(u.getId()) != -1) {
                        PassageiroDAO mdao = new PassageiroDAO();
                        Passageiro m;
                        int id = mdao.verificaPassageiro(u.getId());
                        m = mdao.buscar(id);
                        
                        text = text+"Login: "+ m.getLogin()+"\nEndereço: "+m.getEnderecoResidencia()+"\n";
                    }
                }
                resultadoPassageiroNome.setText(text);

            }
            else {
                JOptionPane.showMessageDialog(null, "Passageiro não encontrado!");
            }
        }
    }//GEN-LAST:event_buscaPassageiroNomeKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        Mot_passDAO mot = new Mot_passDAO();
        Passageiro p = (Passageiro)botaoRemove.getSelectedItem();
        mot.exclui(motoristaID, p.getId_passageiro());
                
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        confirmarCombo.removeAllItems();
        Hor_motDAO hdao = new Hor_motDAO();
        LinkedList ll = hdao.mostrarHorarioMotorista(motoristaID);
        Iterator i = ll.iterator();
        while (i.hasNext()) {
            Horario h = (Horario)i.next();
            if (!hdao.estaAberto(h.getId())) {
                confirmarCombo.addItem(h);
            }
        }

        CardLayout cl = (CardLayout) Tela3.getLayout();
        cl.show(Tela3, "confirmacao");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        desconfirmaCombo.removeAllItems();
        Hor_motDAO hdao = new Hor_motDAO();
        LinkedList ll = hdao.mostrarHorarioMotorista(motoristaID);
        Iterator i = ll.iterator();
        while (i.hasNext()) {
            Horario h = (Horario)i.next();
            if (hdao.estaAberto(h.getId())) {
                desconfirmaCombo.addItem(h);
            }
        }
        
        CardLayout cl = (CardLayout) Tela3.getLayout();
        cl.show(Tela3, "desconfirmar");
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Horario h = (Horario)confirmarCombo.getSelectedItem();
        Hor_motDAO hmot = new Hor_motDAO();
        hmot.abrirConfirmacao(motoristaID, hmot.getIdHor(h.getId()));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Horario h = (Horario)desconfirmaCombo.getSelectedItem();
        Hor_motDAO hmot = new Hor_motDAO();
        LinkedList ll = hmot.fecharConfirmacao(motoristaID, hmot.getIdHor(h.getId()), h.getId());
        Iterator i = ll.iterator();
        String conf = "Passageiros confirmados:";
        while (i.hasNext()) {
            Passageiro p = (Passageiro)i.next();
            conf = conf + "\n"+p.getNome();
        }
        JOptionPane.showMessageDialog(null, conf);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        removerHorarioCombo.removeAllItems();
        Hor_motDAO hdao = new Hor_motDAO();
        LinkedList ll = hdao.mostrarHorarioMotorista(motoristaID);
        Iterator i = ll.iterator();
        while (i.hasNext()) {
            Horario h = (Horario)i.next();
            removerHorarioCombo.addItem(h);   
        }
  
        CardLayout cl = (CardLayout) Tela3.getLayout();
        cl.show(Tela3, "rmhr");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Hor_motDAO mot = new Hor_motDAO();
        Horario h;
        h = (Horario)removerHorarioCombo.getSelectedItem();
        mot.excluir(mot.getIdHor(h.getId()), motoristaID);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        gerarContratoCombo.removeAllItems();
        Mot_passDAO udao = new Mot_passDAO();
        LinkedList ll = udao.passageiros(motoristaID);
        Iterator i = ll.iterator();
        if (!ll.isEmpty()) {
            PassageiroDAO p = new PassageiroDAO();
            Passageiro u;
            while (i.hasNext()) {
                u = (Passageiro) i.next();

                gerarContratoCombo.addItem(u);

            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Não há passageiros na sua lista!");
        }
        CardLayout cl = (CardLayout) Tela3.getLayout();
        cl.show(Tela3, "gerarContrato");
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //codigo gerar contrato
        MotoristaDAO mot = new MotoristaDAO();
        Passageiro p = (Passageiro)gerarContratoCombo.getSelectedItem();
        Motorista m = mot.buscar(motoristaID);
        Document document = new Document();
        try {
            try {
                PdfWriter.getInstance(document, new FileOutputStream("contrato_"+p.getLogin()+".pdf"));
                document.open();
                Paragraph par = new Paragraph();
                par.add("CONTRATO PARTICULAR DE PRESTAÇÃO DE SERVIÇOS DE TRANSPORTE");
                par.setAlignment(Element.ALIGN_JUSTIFIED);
                par.setIndentationLeft(50);
                document.add(par);
                document.add(new Paragraph (" "));
                document.add(new Paragraph (" "));
                document.add(new Paragraph (" "));
                document.add(new Paragraph (" "));
                document.add(new Paragraph (" "));
                document.add(new Paragraph (" "));
                Paragraph par2 = new Paragraph();
                par2.add("Pelo presente instrumento particular de contrato de prestação de serviços de Transporte Escolar, de um lado o(a) Sr(a) "+m.getNome()+" CPF " +m.getCpf()+", motorista de passageiros, residente em "+m.getEnderecoResidencia()+" denominado CONTRATADO, e de outro o(a) Sr(a) "+p.getNome()+" CPF "+p.getCpf()+", passageiro(a), residente em "+p.getEnderecoResidencia()+", doravante denominado CONTRATANTE, tem entre si justo e contratado o seguinte: O CONTRATADO compromete-se a transportar o(a) passageiro(a) cadastrado acima de sua residência à sua Instituição de Ensino e vice-versa, durante o período normal de aulas do semestre letivo com exclusão de domingos ou feriados."
                        );
                par2.setAlignment(Element.ALIGN_JUSTIFIED);
                par2.setIndentationLeft(20);
                document.add(par2);
                document.add(new Paragraph (" "));
                document.add(new Paragraph (" "));
                document.add(new Paragraph (" "));
                document.add(new Paragraph (" "));
                document.add(new Paragraph (" "));
                document.add(new Paragraph (" "));
                document.add(new Paragraph (" "));
                Paragraph par9 = new Paragraph();
                par9.setIndentationLeft(20);
                par9.add("_____________________________");
                document.add(par9);
                Paragraph par4 = new Paragraph();
                par4.setIndentationLeft(20);
                par4.add(m.getNome());
                document.add(par4);
                Paragraph par3 = new Paragraph();
                par3.setIndentationLeft(20);
                par3.add("CONTRATADO");
                document.add(par3);
                document.add(new Paragraph (" "));
                Paragraph par10 = new Paragraph();
                par10.setIndentationLeft(20);
                par10.add("_____________________________");
                document.add(par10);
                Paragraph par5 = new Paragraph();
                par5.setIndentationLeft(20);
                par5.add(p.getNome());
                document.add(par5);
                Paragraph par6 = new Paragraph();
                par6.setIndentationLeft(20);
                par6.add("CONTRATANTE");
                document.add(par6);
                document.add(new Paragraph (" "));
                document.add(new Paragraph (" "));
                Paragraph par7 = new Paragraph();
                par7.setIndentationLeft(20);
                par7.add("___/___/___");
                document.add(par7);
                Paragraph par8 = new Paragraph();
                par8.setIndentationLeft(20);
                par8.add("DATA");
                document.add(par8);
                
            } catch (FileNotFoundException ex) {
                System.out.println("Error:"+ex);
            }
        } catch (DocumentException ex) {
            System.out.println("Error:"+ex);
        }finally {
            document.close();
        }
        
        try {
            Desktop.getDesktop().open(new File("contrato_"+p.getLogin()+".pdf"));
        } catch (IOException ex) {
            System.out.println("Error:"+ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void buscaPassageiroNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaPassageiroNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaPassageiroNomeActionPerformed

    public void recebeID (int id) {
        this.motoristaID = id;
        MotoristaDAO pdao = new MotoristaDAO();
        Motorista p;
        p = pdao.buscar(motoristaID);
        bemVindoLabel.setText("Seja bem vindo(a) " + p.getNome()+",");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaMotorista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane AdicionarHorario;
    private javax.swing.JScrollPane AdicionarPassageiro;
    private javax.swing.JScrollPane BuscarPassageiroNome;
    private javax.swing.JScrollPane Confirmacao;
    private javax.swing.JScrollPane Desconfirmar;
    private javax.swing.JScrollPane GerarContrato;
    private javax.swing.JScrollPane Informações;
    private javax.swing.JScrollPane Inicio;
    private javax.swing.JScrollPane MensagensEnviadas;
    private javax.swing.JScrollPane MensagensRecebidas;
    private javax.swing.JScrollPane MostrarHorario;
    private javax.swing.JButton NovaMensagem;
    private javax.swing.JComboBox<Object> PassageirosComboBox;
    private javax.swing.JScrollPane RemoverHorario;
    private javax.swing.JScrollPane RemoverPassageiro;
    private javax.swing.JPanel Tela3;
    private javax.swing.JLabel bemVindoLabel;
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JComboBox<Object> botaoRemove;
    private javax.swing.JTextField buscaNome;
    private javax.swing.JTextField buscaPassageiroNome;
    private javax.swing.JComboBox<Object> confirmarCombo;
    private javax.swing.JComboBox<Object> desconfirmaCombo;
    private javax.swing.JComboBox<String> diaCombo;
    private javax.swing.JComboBox<Object> gerarContratoCombo;
    private javax.swing.JFormattedTextField horaFinalCad;
    private javax.swing.JFormattedTextField horaInicioCad;
    private javax.swing.JTextArea informacoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JComboBox<Object> removerHorarioCombo;
    private javax.swing.JTextArea resultadoPassageiroNome;
    private javax.swing.JTable tabelaEnviadas;
    private javax.swing.JTable tabelaHorarioIF;
    private javax.swing.JTable tabelaRecebidas;
    // End of variables declaration//GEN-END:variables
}
